#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 AppGrid Contributors
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Regenerates CHANGELOG.md across four commit ranges so every tag in every
# branch lineage gets rendered:
#   1. v1.9.0-rc.1..maintenance/1.9.x — the 1.9.x release line (rc.2..rc.N),
#                                  tagged on this branch, not main. main carries
#                                  the diverged 1.10 dev work and is excluded
#                                  here so the 1.9.x changelog stays 1.9-only.
#   2. v1.8.0..v1.9.0-rc.1       — the 1.9.0-rc.1 section.
#   3. v1.8.0..maintenance/1.8.x — 1.8.x patch releases (1.8.1..1.8.5),
#                                  tagged on the maintenance branch, not main.
#   4. <root>..v1.8.0            — everything up to and including v1.8.0
#                                  (reachable from main).
#
# A single `git cliff` call would walk only the current branch and miss
# tags reachable through sibling branches. Concatenating the ranges (in
# latest-first order) gives a complete history.
#
# Runs --offline so cliff doesn't try to enrich commits via the GitHub API.
# Some refs (maintenance branches) live locally only and would 404 against
# api.github.com. PR numbers still render — the Conventional Commits already
# carry "(#N)" in their messages.

set -euo pipefail

cd "$(dirname "$0")/.."

ROOT=$(git rev-list --max-parents=0 main | tail -1)

{
    printf '# Changelog\n\n'
    printf '<!-- Auto-generated by scripts/changelog.sh from Conventional Commits.\n'
    printf '     Hand-edits get clobbered on the next run. Put release narrative\n'
    printf '     in the GitHub release notes (gh release create) instead. -->\n\n'
    printf 'All notable changes to AppGrid are documented here.\n\n'
    git cliff --offline --strip all v1.9.0-rc.1..maintenance/1.9.x
    git cliff --offline --strip all v1.8.0..v1.9.0-rc.1
    git cliff --offline --strip all v1.8.0..maintenance/1.8.x
    git cliff --offline --strip all "${ROOT}..v1.8.0"
} > CHANGELOG.md

echo "wrote CHANGELOG.md ($(wc -l < CHANGELOG.md) lines)"
