/*
    SPDX-FileCopyrightText: 2026 AppGrid Contributors
    SPDX-License-Identifier: GPL-2.0-or-later
*/

#include "appgridpanelplugin.h"

#include "popupsizepolicy.h"

#include <KConfigGroup>
#include <QTimer>

namespace
{
// Per-instance keys (this applet's own config) and the global keys (shared
// across panel instances) for the popup geometry handshake.
constexpr QLatin1String kPopupWidth{"popupWidth"};
constexpr QLatin1String kPopupHeight{"popupHeight"};
constexpr QLatin1String kPopupSizeOwner{"popupSizeOwner"};
constexpr QLatin1String kGlobalPopupWidth{"appgridPopupWidth"};
constexpr QLatin1String kGlobalPopupHeight{"appgridPopupHeight"};
}

AppGridPanelPlugin::AppGridPanelPlugin(QObject *parent, const KPluginMetaData &data, const QVariantList &args)
    : AppGridPlugin(parent, data, args)
{
    m_useNativeActivation = true;

    // Deferred to ctor-completion so Plasma has finished wiring this applet
    // into its containment slot's config space before we read or write it.
    QTimer::singleShot(0, this, &AppGridPanelPlugin::restorePopupSizeIfStranger);
}

AppGridPanelPlugin::~AppGridPanelPlugin()
{
    // Alternatives-switch destroys the applet synchronously without firing
    // the expanded=false path that QML hooks into. Persist here so the
    // user's current size always reaches globalConfig before instance
    // death, no matter how the destruction was triggered.
    persistPopupSize();
}

void AppGridPanelPlugin::restorePopupSizeIfStranger()
{
    auto inst = config();
    auto global = globalConfig();

    const int instW = inst.readEntry(kPopupWidth, -1);
    const int instH = inst.readEntry(kPopupHeight, -1);
    const QString tag = inst.readEntry(kPopupSizeOwner, QString());
    const int globalW = global.readEntry(kGlobalPopupWidth, -1);
    const int globalH = global.readEntry(kGlobalPopupHeight, -1);

    const auto action = PopupSizePolicy::decideRestore(instW, instH, tag, globalW, globalH);
    switch (action.kind) {
    case PopupSizePolicy::RestoreAction::Keep:
        return;
    case PopupSizePolicy::RestoreAction::Adopt:
        inst.writeEntry(kPopupWidth, action.width);
        inst.writeEntry(kPopupHeight, action.height);
        inst.writeEntry(kPopupSizeOwner, PopupSizePolicy::ownerTag(action.width, action.height));
        break;
    case PopupSizePolicy::RestoreAction::Clear:
        // No trustworthy size anywhere — clear the foreign keys so AppletPopup
        // falls back to GridPanel's implicitWidth/Height instead of inheriting
        // the previous launcher's geometry.
        inst.deleteEntry(kPopupWidth);
        inst.deleteEntry(kPopupHeight);
        inst.deleteEntry(kPopupSizeOwner);
        break;
    }
    inst.sync();
}

void AppGridPanelPlugin::persistPopupSize()
{
    auto inst = config();
    auto global = globalConfig();

    const int w = inst.readEntry(kPopupWidth, 0);
    const int h = inst.readEntry(kPopupHeight, 0);
    if (!PopupSizePolicy::isPersistable(w, h)) {
        return;
    }

    global.writeEntry(kGlobalPopupWidth, w);
    global.writeEntry(kGlobalPopupHeight, h);
    global.sync();

    inst.writeEntry(kPopupSizeOwner, PopupSizePolicy::ownerTag(w, h));
    inst.sync();
}

// Metadata embedded Id-free (generated by CMake from metadata-panel.json.in
// with the KPlugin Id stripped); pluginId comes from the .so filename. The QML
// is compiled into this .so as qrc resources — see appgrid_add_compiled_applet
// in CMakeLists. (#173)
K_PLUGIN_CLASS_WITH_JSON(AppGridPanelPlugin, "metadata-panel.json")

#include "appgridpanelplugin.moc"
